### ISSUE TITLE
avoid duplication

### ISSUE THREAD

**Issue by vladimirstarkov** [andrepolischuk/typographic-less-greater#1]
pls, unpublish this package from npm, to avoid duplication

**Comment by andrepolischuk** [comment]
Done

**Comment by vladimirstarkov** [comment]
which commit?

**Comment by andrepolischuk** [comment]
README update in commit [5453c132](https://github.com/andrepolischuk/typographic-less-greater/tree/5453c132e3a1703ff76cf56951dc84f8879b06fa)

**Comment by vladimirstarkov** [comment]
oh, sorry. I think it is an issue in sibling repo about arrows and math symbols

**Comment by vladimirstarkov** [comment]
actually, current installation wll hot help consumer to install this plugin

**Comment by andrepolischuk** [comment]
May be remove repo?

**Comment by vladimirstarkov** [comment]
If we talk about private repositorires, then it’s fine to keep it, but fix installation section.

On the other side if we talk in term of textr-ecosystem, then it will be better to remove repo, because now it is subset of typographic-math-symbols (thanks to your pull-request one more time!) and duplication is confusing. I understand If you don’t want to remove — it’s fine, then I only ask you to add a link to typographic-math-symbols to help consumeres to solve their practical problems.
